apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web3signer-database
  namespace: signing
  labels:
    app.kubernetes.io/name: web3signer
    app.kubernetes.io/part-of: ethereum-validator-platform
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-database-secrets
  target:
    name: web3signer-database
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: host
      remoteRef:
        key: web3signer-postgres-app
        property: host
    - secretKey: port
      remoteRef:
        key: web3signer-postgres-app
        property: port
    - secretKey: database
      remoteRef:
        key: web3signer-postgres-app
        property: dbname
    - secretKey: username
      remoteRef:
        key: web3signer-postgres-app
        property: username
    - secretKey: password
      remoteRef:
        key: web3signer-postgres-app
        property: password
