apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web3signer
  namespace: signing
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: web3signer
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ethereum
          podSelector:
            matchLabels:
              platform.galaxy-lab/component: validator
      ports:
        - port: 9000
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - port: 9001
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
          podSelector:
            matchLabels:
              cnpg.io/cluster: web3signer-postgres
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
