apiVersion: v1
kind: Service
metadata:
  name: web3signer
  namespace: signing
  labels:
    app.kubernetes.io/name: web3signer
    app.kubernetes.io/part-of: ethereum-validator-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web3signer
  ports:
    - name: signer-http
      port: 9000
      targetPort: signer-http
      protocol: TCP
    - name: metrics
      port: 9001
      targetPort: metrics
      protocol: TCP
