apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-signer-secret-stores.yaml
  - web3signer-security-group-policy.yaml
  - web3signer-migration-security-group-policy.yaml

labels:
  - pairs:
      platform.galaxy-lab/environment: dev
    includeSelectors: false
