apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/web3signer
  - profile.yaml
  - platform-dashboard.yaml
  - geth-lighthouse-dashboard.yaml
  - logging-dashboard.yaml
  - fleet-overview-dashboard.yaml
  - validator-detail-dashboard.yaml
  - signer-slashing-dashboard.yaml

patches:
  - path: signer-telemetry-patch.yaml
