{{- if eq .Values.lifecycleState "active" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ethereum-node.fullname" . }}-engine-jwt
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.engineJwt.secretStoreName }}
  target:
    name: {{ include "ethereum-node.fullname" . }}-engine-jwt
    creationPolicy: Owner
  data:
    - secretKey: jwt.hex
      remoteRef:
        key: {{ .Values.engineJwt.remoteSecretKey }}
        property: {{ .Values.engineJwt.remoteSecretProperty }}
{{- end }}
