{{- if and (eq .Values.lifecycleState "active") .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "ethereum-node.fullname" . }}
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ethereum-node.selectorLabels" . | nindent 6 }}
      platform.galaxy-lab/component: node
  podMetricsEndpoints:
    - port: el-metrics
      interval: 30s
      path: /debug/metrics/prometheus
      relabelings:
        {{- include "ethereum-node.metricRelabelings" (dict "root" . "component" "execution") | nindent 8 }}
    - port: cl-metrics
      interval: 30s
      path: /metrics
      relabelings:
        {{- include "ethereum-node.metricRelabelings" (dict "root" . "component" "consensus") | nindent 8 }}
{{- if .Values.validator.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "ethereum-node.fullname" . }}-validator
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ethereum-node.selectorLabels" . | nindent 6 }}
      platform.galaxy-lab/component: validator
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      relabelings:
        {{- include "ethereum-node.metricRelabelings" (dict "root" . "component" "validator") | nindent 8 }}
{{- end }}
{{- end }}
