{{- if ne .Values.lifecycleState "archived" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ethereum-node.executionPvcName" . }}
  annotations:
    platform.galaxy-lab/network-identity: {{ .Values.networkProfile.identityFingerprint | quote }}
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.execution }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ethereum-node.consensusPvcName" . }}
  annotations:
    platform.galaxy-lab/network-identity: {{ .Values.networkProfile.identityFingerprint | quote }}
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.consensus }}
{{- if .Values.validator.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ethereum-node.validatorPvcName" . }}
  annotations:
    platform.galaxy-lab/network-identity: {{ .Values.networkProfile.identityFingerprint | quote }}
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.validator }}
{{- end }}
{{- end }}
