{{- if eq .Values.lifecycleState "active" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum-node.fullname" . }}
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ethereum-node.selectorLabels" . | nindent 4 }}
    platform.galaxy-lab/component: node
  ports:
    - {name: cl-api, port: 5052, targetPort: cl-api}
    - {name: el-metrics, port: 6060, targetPort: el-metrics}
    - {name: cl-metrics, port: 8008, targetPort: cl-metrics}
---
{{- if .Values.p2p.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum-node.fullname" . }}-{{ .Values.p2p.service.nameSuffix }}
  labels:
    {{- include "ethereum-node.labels" . | nindent 4 }}
  {{- with .Values.p2p.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.p2p.service.type }}
  {{- if and (eq .Values.p2p.service.type "LoadBalancer") .Values.p2p.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.p2p.service.loadBalancerClass | quote }}
  {{- end }}
  {{- if ne .Values.p2p.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.p2p.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.p2p.service.type "LoadBalancer") .Values.p2p.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.p2p.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "ethereum-node.selectorLabels" . | nindent 4 }}
    platform.galaxy-lab/component: node
  ports:
    - {name: el-p2p-tcp, port: 30303, targetPort: el-p2p-tcp, protocol: TCP}
    - {name: el-p2p-udp, port: 30303, targetPort: el-p2p-udp, protocol: UDP}
    - {name: cl-p2p-tcp, port: 9000, targetPort: cl-p2p-tcp, protocol: TCP}
    - {name: cl-p2p-udp, port: 9000, targetPort: cl-p2p-udp, protocol: UDP}
    - {name: cl-quic, port: 9001, targetPort: cl-quic, protocol: UDP}
{{- end }}
{{- end }}
