apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web3signer-postgres-app
  namespace: database
  labels:
    app.kubernetes.io/name: web3signer-postgres
    app.kubernetes.io/component: database-credential-adapter
    app.kubernetes.io/part-of: ethereum-validator-platform
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-database-secrets
  target:
    name: web3signer-postgres-app
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: host
      remoteRef:
        key: eth-validator-platform-dev/signing/web3signer-database
        property: host
    - secretKey: port
      remoteRef:
        key: eth-validator-platform-dev/signing/web3signer-database
        property: port
    - secretKey: dbname
      remoteRef:
        key: eth-validator-platform-dev/signing/web3signer-database
        property: database
    - secretKey: username
      remoteRef:
        key: eth-validator-platform-dev/signing/web3signer-database
        property: username
    - secretKey: password
      remoteRef:
        key: eth-validator-platform-dev/signing/web3signer-database
        property: password
