apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: web3signer-postgres
  namespace: database
  labels:
    app.kubernetes.io/name: web3signer-postgres
    app.kubernetes.io/part-of: ethereum-validator-platform
    platform.galaxy-lab/environment: local
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie@sha256:0f29b435fb501ee534cd0c555d122a6b8e90de477de8e8381c82c5e10d9a9de4
  bootstrap:
    initdb:
      database: web3signer
      owner: web3signer
      dataChecksums: true
  storage:
    storageClass: standard
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
