apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../controllers
  - ingress-nginx-namespace.yaml
  - ingress-nginx-repository.yaml
  - ingress-nginx.yaml
  - aws-load-balancer-controller-repository.yaml
  - aws-load-balancer-controller.yaml
  - grafana-ingress.yaml

patches:
  - path: monitoring-patch.yaml
  - target:
      kind: Namespace
      name: cnpg-system
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cnpg-system
      $patch: delete
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmRepository
      name: cloudnative-pg
    patch: |-
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: cloudnative-pg
        namespace: flux-system
      $patch: delete
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmRepository
      name: grafana
    patch: |-
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: grafana
        namespace: flux-system
      $patch: delete
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: cloudnative-pg
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: cloudnative-pg
        namespace: cnpg-system
      $patch: delete
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: loki
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: loki
        namespace: observability
      $patch: delete
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: alloy
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: alloy
        namespace: observability
      $patch: delete
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: loki
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: loki
        namespace: observability
      $patch: delete
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: alloy
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: alloy
        namespace: observability
      $patch: delete

labels:
  - pairs:
      platform.galaxy-lab/environment: dev
    includeSelectors: false
