apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: aws-rds-ca
    files:
      - rds-ca.pem=us-west-2-rds-ca-rsa2048-g1.pem
generatorOptions:
  disableNameSuffixHash: true
