apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - repositories.yaml
  - external-secrets.yaml
  - cloudnative-pg.yaml
  - monitoring.yaml
  - logging-loki.yaml
  - logging-alloy.yaml
  - logging-networkpolicies.yaml
