apiVersion: platform.galaxy-lab/v1alpha1
kind: ServiceProfile
metadata:
  name: dedicated-geth-teku
spec:
  executionClient: geth
  consensusClient: teku
  tenancy: dedicated
  resourceProfile: local-real-node
  signingAllowed: true
