apiVersion: platform.galaxy-lab/v1alpha1
kind: ServiceProfile
metadata:
  name: dedicated-besu-teku
spec:
  executionClient: besu
  consensusClient: teku
  tenancy: dedicated
  resourceProfile: local-real-node
  signingAllowed: true
