apiVersion: platform.galaxy-lab/v1alpha1
kind: ServiceProfile
metadata:
  name: dedicated-nethermind-lighthouse
spec:
  executionClient: nethermind
  consensusClient: lighthouse
  tenancy: dedicated
  resourceProfile: local-real-node
  signingAllowed: true
