apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web3signer-schema
  namespace: database
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: web3signer-schema
      app.kubernetes.io/component: database-migration
  policyTypes: ["Ingress", "Egress"]
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: web3signer-postgres
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
