apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ebs-gp3-storage-class.yaml
  - aws-secret-stores.yaml
  - default-deny.yaml
  - web3signer-security-group-policy.yaml
  - web3signer-migration-security-group-policy.yaml

labels:
  - pairs:
      platform.galaxy-lab/environment: dev
    includeSelectors: false
