#!/usr/bin/env python3
"""Compile the declarative catalog into Flux-managed local Helm releases.

This is intentionally a narrow Phase 3 adapter. It projects every supported
assignment into the in-repository ethereum-node chart, but it never enables a
validator client or signing. The catalog remains the operator-facing source of
truth; generated files are committed so Flux sees a reviewable, deterministic
desired state and CI can reject projection drift.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
APPLICATIONS = ROOT / "applications"
OUTPUT_DIRECTORY = ROOT / "platform" / "apps" / "local" / "assignments"
GENERATED_HEADER = (
    "# Generated by tools/render_local_assignments.py from applications/.\n"
    "# Do not edit by hand; change the catalog and rerun the renderer.\n"
)

SUPPORTED_EXECUTION_CLIENTS = {"geth"}
SUPPORTED_CONSENSUS_CLIENTS = {"lighthouse"}


class ProjectionError(ValueError):
    """Catalog state cannot be represented by the current local adapter."""


def default_node_pair_ref(validator_ref: str) -> str:
    """Return the stable DNS-safe resource identity for a validator pair.

    The projection must choose this identity before the first activation. If a
    stopped release used the assignment name and activation later introduced a
    nodePairRef, Helm would see every workload and PVC as a replacement.
    """

    candidate = f"pair-{validator_ref}"
    if len(candidate) <= 63:
        return candidate
    suffix = hashlib.sha256(candidate.encode("utf-8")).hexdigest()[:8]
    return f"{candidate[:54]}-{suffix}"


def load_catalog(root: Path = ROOT) -> dict[str, dict[str, dict[str, Any]]]:
    """Load catalog documents keyed by kind and metadata.name."""

    catalog: dict[str, dict[str, dict[str, Any]]] = {}
    applications = root / "applications"
    for path in sorted(applications.rglob("*.yaml")):
        with path.open(encoding="utf-8") as stream:
            for document in yaml.safe_load_all(stream):
                if document is None:
                    continue
                kind = document.get("kind")
                name = document.get("metadata", {}).get("name")
                if not kind or not name:
                    raise ProjectionError(f"{path}: catalog document is missing kind or metadata.name")
                by_name = catalog.setdefault(kind, {})
                if name in by_name:
                    raise ProjectionError(f"duplicate {kind} metadata.name {name!r}")
                by_name[name] = document
    return catalog


def chart_lifecycle(catalog_lifecycle: str) -> str:
    """Map the richer catalog lifecycle onto the chart's runtime states.

    Only a fully `active` assignment launches compute. Intermediate and
    failed-safe states fail closed to the stopped chart state. `archived`
    removes the chart's replaceable chain-data PVC declarations, but no
    workflow in this initial slice is allowed to request it.
    """

    if catalog_lifecycle == "active":
        return "active"
    if catalog_lifecycle == "archived":
        return "archived"
    return "stopped"


def build_release(
    assignment_name: str,
    catalog: dict[str, dict[str, dict[str, Any]]],
) -> dict[str, Any]:
    """Build one local Flux HelmRelease from relational catalog state."""

    try:
        assignment = catalog["ValidatorAssignment"][assignment_name]
    except KeyError as error:
        raise ProjectionError(f"unknown ValidatorAssignment {assignment_name!r}") from error

    spec = assignment["spec"]
    if spec["signingEnabled"]:
        raise ProjectionError(
            f"ValidatorAssignment/{assignment_name}: the local projection is non-signing only"
        )

    validator_name = spec["validatorRef"]
    profile_name = spec["serviceProfileRef"]
    try:
        identity = catalog["ValidatorIdentity"][validator_name]
    except KeyError as error:
        raise ProjectionError(
            f"ValidatorAssignment/{assignment_name}: unknown validatorRef {validator_name!r}"
        ) from error
    try:
        profile = catalog["ServiceProfile"][profile_name]
    except KeyError as error:
        raise ProjectionError(
            f"ValidatorAssignment/{assignment_name}: unknown serviceProfileRef {profile_name!r}"
        ) from error

    execution_client = profile["spec"]["executionClient"]
    consensus_client = profile["spec"]["consensusClient"]
    if execution_client not in SUPPORTED_EXECUTION_CLIENTS:
        raise ProjectionError(
            f"ServiceProfile/{profile_name}: execution client {execution_client!r} has no local adapter"
        )
    if consensus_client not in SUPPORTED_CONSENSUS_CLIENTS:
        raise ProjectionError(
            f"ServiceProfile/{profile_name}: consensus client {consensus_client!r} has no local adapter"
        )

    identity_spec = identity["spec"]
    customer_name = identity_spec["customerRef"]
    if customer_name not in catalog.get("Customer", {}):
        raise ProjectionError(
            f"ValidatorIdentity/{validator_name}: unknown customerRef {customer_name!r}"
        )

    runtime_lifecycle = chart_lifecycle(spec["lifecycle"])
    node_pair_name = spec.get("nodePairRef")
    if runtime_lifecycle == "active" and not node_pair_name:
        raise ProjectionError(
            f"ValidatorAssignment/{assignment_name}: active state requires nodePairRef"
        )
    # Stopped assignments may predate nodePairRef in the catalog. Derive the
    # same stable identity the lifecycle transition will persist so the first
    # activation does not rename resources or replace chain-data PVCs.
    node_pair_name = node_pair_name or default_node_pair_ref(validator_name)

    return {
        "apiVersion": "helm.toolkit.fluxcd.io/v2",
        "kind": "HelmRelease",
        "metadata": {
            "name": assignment_name,
            "namespace": "ethereum",
            "labels": {
                "app.kubernetes.io/part-of": "ethereum-validator-platform",
                "platform.galaxy-lab/assignment-id": assignment_name,
                "platform.galaxy-lab/validator-id": validator_name,
            },
        },
        "spec": {
            "interval": "10m",
            "timeout": "10m",
            "chart": {
                "spec": {
                    "chart": "./charts/ethereum-node",
                    "sourceRef": {
                        "kind": "GitRepository",
                        "name": "flux-system",
                        "namespace": "flux-system",
                    },
                    "interval": "10m",
                    "reconcileStrategy": "Revision",
                }
            },
            # A first install in stopped state intentionally has no Pod to bind
            # WaitForFirstConsumer PVCs. Waiting would deadlock the HelmRelease.
            # An active first install still waits; stopped -> active is an
            # upgrade and uses the normal (waiting) upgrade action below.
            "install": {
                "disableWait": runtime_lifecycle != "active",
                "remediation": {"retries": 3},
            },
            "upgrade": {"remediation": {"retries": 3}},
            "values": {
                "fullnameOverride": node_pair_name,
                "lifecycleState": runtime_lifecycle,
                "network": identity_spec["network"],
                "executionClient": execution_client,
                "consensusClient": consensus_client,
                "telemetry": {
                    "cluster": "kind-eth-validator-local",
                    "environment": "local",
                },
                "identity": {
                    "customerId": customer_name,
                    "validatorId": validator_name,
                    "assignmentId": assignment_name,
                },
                "validator": {
                    "enabled": False,
                    "slashingProtectionConfirmed": False,
                },
            },
        },
    }


def yaml_text(document: dict[str, Any]) -> str:
    return GENERATED_HEADER + yaml.safe_dump(document, sort_keys=False, width=120)


def rendered_files(
    catalog: dict[str, dict[str, dict[str, Any]]],
) -> dict[str, str]:
    """Return every generated filename and its canonical content."""

    assignments = sorted(catalog.get("ValidatorAssignment", {}))
    if not assignments:
        raise ProjectionError("catalog contains no ValidatorAssignment documents")

    files = {
        f"{name}.yaml": yaml_text(build_release(name, catalog))
        for name in assignments
    }
    kustomization = {
        "apiVersion": "kustomize.config.k8s.io/v1beta1",
        "kind": "Kustomization",
        "resources": [f"{name}.yaml" for name in assignments],
    }
    files["kustomization.yaml"] = yaml_text(kustomization)
    return files


def write_projection(
    files: dict[str, str],
    output_directory: Path = OUTPUT_DIRECTORY,
) -> None:
    output_directory.mkdir(parents=True, exist_ok=True)
    expected = set(files)
    for path in output_directory.glob("*.yaml"):
        if path.name not in expected:
            path.unlink()
    for filename, content in files.items():
        (output_directory / filename).write_text(content, encoding="utf-8")


def projection_errors(
    files: dict[str, str],
    output_directory: Path = OUTPUT_DIRECTORY,
) -> list[str]:
    errors: list[str] = []
    expected = set(files)
    existing = {path.name for path in output_directory.glob("*.yaml")}
    for missing in sorted(expected - existing):
        errors.append(f"missing generated file: {output_directory / missing}")
    for stale in sorted(existing - expected):
        errors.append(f"stale generated file: {output_directory / stale}")
    for filename in sorted(expected & existing):
        actual = (output_directory / filename).read_text(encoding="utf-8")
        if actual != files[filename]:
            errors.append(f"generated file differs from catalog: {output_directory / filename}")
    return errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed generated files differ instead of writing them",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        files = rendered_files(load_catalog())
    except ProjectionError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.check:
        errors = projection_errors(files)
        if errors:
            for error in errors:
                print(f"ERROR: {error}", file=sys.stderr)
            return 1
        print(f"Verified {len(files) - 1} generated local assignment release(s).")
        return 0

    write_projection(files)
    print(f"Rendered {len(files) - 1} local assignment release(s) into {OUTPUT_DIRECTORY.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
