apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/web3signer
  - ../base/aws-rds-ca
  - profile.yaml

patches:
  - path: signer-telemetry-patch.yaml
  - target:
      group: external-secrets.io
      version: v1
      kind: ExternalSecret
      name: web3signer-database
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: aws-database-secrets
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: eth-validator-platform-dev/signing/web3signer-database
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: eth-validator-platform-dev/signing/web3signer-database
      - op: replace
        path: /spec/data/2/remoteRef/key
        value: eth-validator-platform-dev/signing/web3signer-database
      - op: replace
        path: /spec/data/3/remoteRef/key
        value: eth-validator-platform-dev/signing/web3signer-database
      - op: replace
        path: /spec/data/4/remoteRef/key
        value: eth-validator-platform-dev/signing/web3signer-database
      - op: replace
        path: /spec/data/2/remoteRef/property
        value: database
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: web3signer
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/10
        value: --slashing-protection-db-url=jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=verify-full&sslrootcert=/var/run/aws-rds-ca/rds-ca.pem
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: aws-rds-ca
          mountPath: /var/run/aws-rds-ca
          readOnly: true
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: aws-rds-ca
          configMap:
            name: aws-rds-ca
  - target:
      version: v1
      kind: ConfigMap
      name: aws-rds-ca
    patch: |-
      - op: add
        path: /metadata/namespace
        value: signing
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: web3signer
    patch: |-
      - op: replace
        path: /spec/egress/0
        value:
          to:
            - ipBlock:
                cidr: 10.42.0.0/16
          ports:
            - port: 5432
              protocol: TCP
labels:
  - pairs:
      platform.galaxy-lab/environment: dev
    includeSelectors: false
