apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web3signer-validator-keystore
  namespace: signing
  labels:
    app.kubernetes.io/name: web3signer
    app.kubernetes.io/part-of: ethereum-validator-platform
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-signing-secrets
  target:
    name: web3signer-validator-keystore
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        validator.json: "{{ .keystore }}"
        validator.password: "{{ .password }}"
        validator.yaml: |
          type: "file-keystore"
          keyType: "BLS"
          keystoreFile: "/var/run/web3signer/keys/validator.json"
          keystorePasswordFile: "/var/run/web3signer/keys/validator.password"
  data:
    - secretKey: keystore
      remoteRef:
        key: eth-validator-platform-dev/signing/validator-keystore
        property: keystore
    - secretKey: password
      remoteRef:
        key: eth-validator-platform-dev/signing/validator-keystore
        property: password
